config/routes.rb
CuponValpo::Application.routes.draw do
  resources :empresas

  resources :cupons

  root :to => 'cupons#index'

end

app/models/cupon.rb
class Cupon < ActiveRecord::Base
  attr_accessible :descripcion, :foto, :nombre, :precio_dcto, :precio_normal, :stock, :validez, :empresa_id

  belongs_to :empresa  
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  attr_accessible :logo, :nombre

  has_many :cupons, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cupons_controller.rb
class CuponsController < ApplicationController
  # GET /cupons
  # GET /cupons.json
  def index
    @cupons = Cupon.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @cupons }
    end
  end

  # GET /cupons/1
  # GET /cupons/1.json
  def show
    @cupon = Cupon.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @cupon }
    end
  end

  # GET /cupons/new
  # GET /cupons/new.json
  def new
    @cupon = Cupon.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @cupon }
    end
  end

  # GET /cupons/1/edit
  def edit
    @cupon = Cupon.find(params[:id])
  end

  # POST /cupons
  # POST /cupons.json
  def create
    @cupon = Cupon.new(params[:cupon])

    respond_to do |format|
      if @cupon.save
        format.html { redirect_to @cupon, :notice => 'Cupon was successfully created.' }
        format.json { render :json => @cupon, :status => :created, :location => @cupon }
      else
        format.html { render :action => "new" }
        format.json { render :json => @cupon.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cupons/1
  # PUT /cupons/1.json
  def update
    @cupon = Cupon.find(params[:id])

    respond_to do |format|
      if @cupon.update_attributes(params[:cupon])
        format.html { redirect_to @cupon, :notice => 'Cupon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @cupon.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cupons/1
  # DELETE /cupons/1.json
  def destroy
    @cupon = Cupon.find(params[:id])
    @cupon.destroy

    respond_to do |format|
      format.html { redirect_to cupons_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  # GET /empresas
  # GET /empresas.json
  def index
    @empresas = Empresa.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @empresas }
    end
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
    @empresa = Empresa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @empresa }
    end
  end

  # GET /empresas/new
  # GET /empresas/new.json
  def new
    @empresa = Empresa.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @empresa }
    end
  end

  # GET /empresas/1/edit
  def edit
    @empresa = Empresa.find(params[:id])
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(params[:empresa])

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to @empresa, :notice => 'Empresa was successfully created.' }
        format.json { render :json => @empresa, :status => :created, :location => @empresa }
      else
        format.html { render :action => "new" }
        format.json { render :json => @empresa.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /empresas/1
  # PUT /empresas/1.json
  def update
    @empresa = Empresa.find(params[:id])

    respond_to do |format|
      if @empresa.update_attributes(params[:empresa])
        format.html { redirect_to @empresa, :notice => 'Empresa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @empresa.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa = Empresa.find(params[:id])
    @empresa.destroy

    respond_to do |format|
      format.html { redirect_to empresas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cupons_helper.rb
module CuponsHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/views/cupons/_form.html.erb
<%= form_for @cupon, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :precio_normal, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :precio_normal, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :precio_dcto, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :precio_dcto, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :descripcion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :descripcion, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :validez, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :validez, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :stock, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :stock, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :foto, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :foto, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :empresa_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :empresa_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                cupons_path, :class => 'btn' %>
  </div>
<% end %>

app/views/cupons/edit.html.erb
<%- model_class = Cupon -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cupons/index.html.erb
<%- model_class = Cupon -%>
<div class="page-header">
  <h1>Cupones</h1>
</div>
<ul class="thumbnails">
    <% @cupons.each do |cupon| %>
      <li class="span4">
       <div class="thumbnail">
        <%= image_tag cupon.foto %>
        <%= cupon.nombre %>
        <%= cupon.precio_normal %>
        <%= cupon.precio_dcto %>
          <%= link_to 'Ver Oferta',
                      cupon_path(cupon), :class => 'btn btn-success' %>
          <% link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cupon_path(cupon), :class => 'btn btn-mini' %>
          <% link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cupon_path(cupon),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
       </div>
      </li>
    <% end %>
</ul>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cupon_path,
            :class => 'btn btn-primary' %>

app/views/cupons/new.html.erb
<%- model_class = Cupon -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cupons/show.html.erb
<%- model_class = Cupon -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @cupon.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:precio_normal) %>:</strong></dt>
  <dd><%= @cupon.precio_normal %></dd>
  <dt><strong><%= model_class.human_attribute_name(:precio_dcto) %>:</strong></dt>
  <dd><%= @cupon.precio_dcto %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descripcion) %>:</strong></dt>
  <dd><%= @cupon.descripcion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:validez) %>:</strong></dt>
  <dd><%= @cupon.validez %></dd>
  <dt><strong><%= model_class.human_attribute_name(:stock) %>:</strong></dt>
  <dd><%= @cupon.stock %></dd>
  <dt><strong><%= model_class.human_attribute_name(:foto) %>:</strong></dt>
  <dd><%= image_tag @cupon.foto %></dd>
  <dt><strong><%= model_class.human_attribute_name(:empresa_id) %>:</strong></dt>
  <dd><%= @cupon.empresa.nombre %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              cupons_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cupon_path(@cupon), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cupon_path(@cupon),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/empresas/_form.html.erb
<%= form_for(@empresa) do |f| %>
  <% if @empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empresa.errors.count, "error") %> prohibited this empresa from being saved:</h2>

      <ul>
      <% @empresa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :logo %><br />
    <%= f.text_field :logo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/empresas/edit.html.erb
<h1>Editing empresa</h1>

<%= render 'form' %>

<%= link_to 'Show', @empresa %> |
<%= link_to 'Back', empresas_path %>

app/views/empresas/index.html.erb
<h1>Listing empresas</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Logo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @empresas.each do |empresa| %>
  <tr>
    <td><%= empresa.nombre %></td>
    <td><%= empresa.logo %></td>
    <td><%= link_to 'Show', empresa %></td>
    <td><%= link_to 'Edit', edit_empresa_path(empresa) %></td>
    <td><%= link_to 'Destroy', empresa, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Empresa', new_empresa_path %>

app/views/empresas/new.html.erb
<h1>New empresa</h1>

<%= render 'form' %>

<%= link_to 'Back', empresas_path %>

app/views/empresas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @empresa.nombre %>
</p>

<p>
  <b>Logo:</b>
  <%= @empresa.logo %>
</p>


<%= link_to 'Edit', edit_empresa_path(@empresa) %> |
<%= link_to 'Back', empresas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CuponValpo" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">CuponValpo</a>
          <div class="container nav-collapse">
            <ul class="nav">
                <li><%= link_to "Home", "/"  %></li>
                <li><%= link_to "Cupones", "/cupons"  %></li>
                <li><%= link_to "Empresas", "/empresas"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Home", "/"  %></li>
                <li><%= link_to "Cupones", "/cupons"  %></li>
                <li><%= link_to "Empresas", "/empresas"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>